"""Plan 1 finish line: the hero app registers, migrates, and its tool and
widget work end-to-end against a real SQLite database — no LLM involved."""

import sys
from pathlib import Path

from dudamel import Orchestrator
from dudamel.contract.renderers import validate_widget_payload
from dudamel.db import Database
from dudamel.migrate import (
    ensure_app_migrations,
    generate_app_migration,
    upgrade_apps,
    upgrade_core,
)

sys.path.insert(0, str(Path(__file__).parent.parent / "examples"))
from workouts import app as workouts_app  # noqa: E402


async def test_hero_app_end_to_end(tmp_path: Path):
    url = f"sqlite+aiosqlite:///{tmp_path}/hero.db"
    orc = Orchestrator(apps=[workouts_app])

    # registration surfaces
    assert set(orc.registry.tools) == {"log_workout"}
    assert [w.id for w in orc.registry.widgets] == ["week_volume"]
    assert [j.id for j in orc.registry.jobs] == ["workouts.evening_summary"]

    # migrate: core (framework-shipped) then apps (autogenerated)
    upgrade_core(url)
    ensure_app_migrations(tmp_path)
    assert generate_app_migration(orc, url, "init", tmp_path) is not None
    upgrade_apps(url, tmp_path)

    # bind db and drive the tool exactly as the Plan 2 router will:
    # coerce string-ish LLM args -> call the tool fn
    db = Database(url)
    workouts_app.bind_database(db)
    tool = orc.registry.tools["log_workout"]
    kwargs = tool.schema.validate(
        {"exercise": "bench", "sets": "3", "reps": "5", "weight_kg": "100"}
    )
    reply = await tool.fn(**kwargs)
    assert reply == "Logged: bench 3x5 @ 100.0kg"

    # widget: pure DB read, validated against its renderer contract
    widget = orc.registry.widgets[0]
    payload = validate_widget_payload(widget.renderer, await widget.fn())
    assert payload.value == 100.0 and payload.unit == "kg"
    await db.engine.dispose()
