class DudamelError(Exception):
    """Base for all framework errors."""


class ToolValidationError(DudamelError):
    """Tool arguments failed validation/coercion. Message is written for the model."""


class UnknownToolOutcome(DudamelError, RuntimeError):
    """A tool call whose side effect may or may not have taken effect.

    Raised instead of an ordinary error when a call was already dispatched
    but its result never came back, so nothing downstream can tell whether
    the mutation landed. The distinct type is what lets a caller phrase the
    result as indeterminate instead of as a failure without matching on the
    prose of the message; the message itself is written for the model.

    Also a `RuntimeError`, because that is what a tool function raising an
    ordinary error already produces, and every existing handler around
    `Tool.fn` -- including the ones that only guarantee "no `BaseException`
    escapes" -- must keep treating this the same way.
    """


class RegistryError(DudamelError):
    """App/tool/widget/job registration problem."""


class RuntimeNotBoundError(DudamelError):
    """A runtime capability (db/llm/notify) used before the run phase bound it."""


class DestructiveMigrationError(DudamelError):
    """Autogenerated migration contains destructive ops and allow_destructive=False."""


class LLMError(DudamelError):
    """A model/provider call failed. Message is safe to surface to the user."""

    def __init__(self, message: str, *, retryable: bool = False) -> None:
        super().__init__(message)
        self.retryable = retryable


class ProviderRequestError(LLMError):
    """The provider rejected the REQUEST itself — a 4xx it will keep
    rejecting (malformed messages, an unusable tool schema, a bad key).

    A subclass rather than a flag on `LLMError` so the router can word the
    two causes apart without matching on prose: an outage is something a
    user can usefully wait out, a rejected request never is. `retryable`
    stays False for every instance — retrying is exactly what does not help.
    """


class BudgetExceededError(DudamelError):
    """The configured daily LLM budget is exhausted; hard stop."""


class AlreadyRunningError(DudamelError, RuntimeError):
    """Another `serve()` already holds the instance lock for this data_dir.

    A DudamelError so `dudamel run` prints it as a clean, actionable one-liner
    (like every other operator condition) rather than framing this expected
    situation as an internal crash with a "re-run with --debug" traceback
    invitation. Also a `RuntimeError`, so callers/tests that predate the typed
    exception and match on `RuntimeError` keep working unchanged.
    """
