class DudamelError(Exception):
    """Base for all framework errors."""


class ToolValidationError(DudamelError):
    """Tool arguments failed validation/coercion. Message is written for the model."""


class RegistryError(DudamelError):
    """App/tool/widget/job registration problem."""


class RuntimeNotBoundError(DudamelError):
    """A runtime capability (db/llm/notify) used before the run phase bound it."""


class DestructiveMigrationError(DudamelError):
    """Autogenerated migration contains destructive ops and allow_destructive=False."""


class LLMError(DudamelError):
    """A model/provider call failed. Message is safe to surface to the user."""

    def __init__(self, message: str, *, retryable: bool = False) -> None:
        super().__init__(message)
        self.retryable = retryable


class BudgetExceededError(DudamelError):
    """The configured daily LLM budget is exhausted; hard stop."""
